-- Enable the pgvector extension to work with embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- Asset Table: The core entity for every file ingested
CREATE TABLE assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    filename TEXT NOT NULL,
    original_path TEXT NOT NULL,
    storage_key TEXT NOT NULL, -- Reference to MinIO/S3 object
    file_size BIGINT NOT NULL,
    mime_type TEXT NOT NULL,
    width INTEGER,
    height INTEGER,
    extension TEXT NOT NULL,
    checksum TEXT, -- For deduplication (MD5/SHA256)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Projects Table: Logical grouping for designers
CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    client_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Junction table for Assets and Projects
CREATE TABLE project_assets (
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    asset_id UUID REFERENCES assets(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, asset_id)
);

-- Asset Metadata: Detailed technical and AI-extracted data
CREATE TABLE asset_metadata (
    asset_id UUID PRIMARY KEY REFERENCES assets(id) ON DELETE CASCADE,
    exif_data JSONB,
    dominant_colors TEXT[], -- Array of Hex codes
    ocr_content TEXT,      -- Text extracted from images/PDFs
    ai_description TEXT,   -- Natural language caption generated by AI
    last_processed_at TIMESTAMP WITH TIME ZONE
);

-- Tags: Both AI-generated and Manual tags
CREATE TABLE tags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    source TEXT DEFAULT 'manual' -- 'manual' or 'ai'
);

-- Junction table for Assets and Tags
CREATE TABLE asset_tags (
    asset_id UUID REFERENCES assets(id) ON DELETE CASCADE,
    tag_id UUID REFERENCES tags(id) ON DELETE CASCADE,
    confidence FLOAT DEFAULT 1.0, -- Confidence score for AI tags
    PRIMARY KEY (asset_id, tag_id)
);

-- Asset Embeddings: Stores high-dimensional vectors for semantic search
CREATE TABLE asset_embeddings (
    asset_id UUID PRIMARY KEY REFERENCES assets(id) ON DELETE CASCADE,
    embedding vector(512) -- 512 is standard for CLIP ViT-B/32
);

-- Create triggers for updated_at
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_assets_modtime
    BEFORE UPDATE ON assets
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();